### ISSUE TITLE
No getDeviceIdentifier method

### ISSUE THREAD

**Issue by JohnyLe** [bugfender/rn-bugfender#11]
Hello,

I couldn't find the method getDeviceIdentifier or another method what can get bugfender id.
Please help!

**Comment by RubenVot** [comment]
Hi @JohnyLe 
getDeviceIdentifier was deprecated in previous versions. You can use now getDeviceUrl and use it as unique identifier as well. 
The difference is that instead of being some random id is a full formed url that links to the concrete device in the Bugfender dashboard (specially useful to create integrations with another services)
Regards!
