### ISSUE TITLE
'React/RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by vananreed** [bugfender/rn-bugfender#3]
After strictly following the installation steps on the Readme, and then attempting to build, I get this preprocessing error: 

'React/RCTBridgeModule.h' file not found

1. In file included from .../node_modules/@bugfender/rn-bugfender/ios/RNBugfender.m:1:

This react native project is ejected from expo, using Expo SDK v32.0.0, and the latest version of BugfenderSDK.framework 
![image](https://user-images.githubusercontent.com/38326813/56690000-6c5cb800-66aa-11e9-9c8a-1dff8260d6d9.png)

**Comment by RubenVot** [comment]
Hi @vananreed, 
I see you are using ExpoKit. We created the RN plugin following the official docs for vanilla RN. 

Fortunately, in the [docs of ExpoKit](https://docs.expo.io/versions/latest/expokit/expokit/) they mention this issue: 

> If the library doesn't support CocoaPods, react-native link may fail to include the library's header files. If you encounter build issues locating the <React/*> headers, you may need to manually add Pods/Headers/Public to the Header Search Paths configuration for your native dependency in Xcode. If you're not familiar with Xcode, search Xcode help for "configure build settings" to get an idea of how those work. Header Search Paths is one such build setting. The target you care to configure is the one created by react-native link inside your Xcode project. You'll want to determine the relative path from your library to Pods/Headers/Public.

Could you please follow the steps in the official docs of Expo and let us know how it worked? We might add some lines about this to our docs as well. 

I hope it helps! 

_Side note: the last time we checked, it was not possible to make RNBugfender compatible with Cocoapods due to changes in RN that were happening at that moment. We had in our roadmap to make compatible in a near future._

**Comment by macfanatic** [comment]
We were able to resolve this with the above mentioned header search paths setting, and we skipped the installation instruction copied from the iOS project regarding the "Bugfender.swift" snippet.  

It's a bit confusing in the RN setup instructions as the RN project ejected from expo is written in Objective-C, so while a bridging header was created and we could import the framework there to make available to Swift, at the end none of it is needed since we're doing all our logging in RN anyway.

Our header search paths on the "RNBugfender.xcodeproj" target look like the following (see screenshot).  We're referencing the React managed via Cocoapods, setup by ExpoKit itself.

```
"$(SRCROOT)/../../../../ios/Pods/Headers/Public"
"$(SRCROOT)/../../../../ios/Pods/Headers/Public/React"
```

![Screen Shot 2019-04-25 at 9 38 29 AM](https://user-images.githubusercontent.com/162970/56740014-0b7ebf80-673e-11e9-8a99-fb6de378a9eb.png)
