### ISSUE TITLE
Require cycle with 2.0.0

### ISSUE THREAD

**Issue by molmutius** [bugfender/rn-bugfender#41]
The following require cycle can be seen with LogBox enabled since 2.0.0

![image](https://user-images.githubusercontent.com/3121980/172778072-6595048e-2426-4e69-a703-f40d3e3ef60d.png)

**Comment by jgimenez** [comment]
Thanks for brining this to our attention. Do you have an example code that we can use to reproduce the issue? I guess this is not happening with our example application, so it might be something application-specific

**Comment by franmontiel** [comment]
Hi @molmutius, I was able to reproduce the warning in react 0.63 (in recent versions it is not happening).

We'll release a new version as soon as possible with the fix for this.

For the moment if you want to get rid of the warning you can use this snippet:
`useEffect(() => LogBox.ignoreLogs(['Require cycle: node_modules/']), []);`

**Comment by franmontiel** [comment]
Version 2.1.0 has just been released with a fix for this issue.
